#spring.application.name=eureka-service
#server.port=8010
#eureka.instance.hostname=peer
###表示是否将自己注册到Eureka Server，默认为true
##eureka.client.register-with-eureka=false
###表示是否从Eureka Server获取注册信息，默认为true。
##eureka.client.fetch-registry=false
###设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
#eureka.client.service-url.defaultZone=http://peer:8010/eureka/,http://peer1:8011/eureka/spring:
  application:
    name: spring-cloud-eureka-service
  server:
    port: 8010
  eureka:
    instance:
      hostname: peer
    client:
      region: china
      register-with-eureka: false
      fetch-registry: false
      availability-zones:
        china: gd,gx
      service-url:
        defaultZone: http://peer:8010/eureka/

